### ISSUE TITLE
The UI doesn't start with Windows

### ISSUE THREAD

**Issue by Sluzyy** [LavamasterYT/AirPods-for-Windows#6]
After I've checked the option to add the AirPods UI for Windows to the Startup Program, it doesn't start as a startup program, doesn't start with windows.

**Comment by LavamasterYT** [comment]
That option adds the service to startup instead of the configurator. If you want to add the configurator to startup, create a shortcut of it, and place the shortcut to C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup
